spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      consumer:
        group-id: payment-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

        properties:
          spring.json.trusted.packages: "*"

  application:
    name: payment-component

  datasource:
    url: jdbc:h2:mem:payment-db
    username: ar
    password:

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

rates:
  rub: ${RUB_VAR:1}
  usd: ${USD_VAR:75}
  eur: ${EUR_VAR:89}

fees:
  threshold-low: ${THRESHOLD_LOW:1000}
  threshold-high: ${THRESHOLD_HIGH:5000}
  rate-low: ${RATE_LOW:0.015}
  rate-mid: ${RATE_MID:0.01}
  rate-high: ${RATE_HIGH:0.005}
