spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/payment_component
    username: payment_user
    password: payment_pswd
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  application:
    name: payment-component

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ms_payment_component

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog_init_v1.01.xml
    default-schema: ms_payment_component
    drop-first: false

kafka:
  payment-events-topic: ${PAYMENT_EVENTS_TOPIC:payment-events}

outbox:
  publisher:
    fixed-delay-ms: 2000

rates:
  rub: ${RUB_VAR:1}
  usd: ${USD_VAR:75}
  eur: ${EUR_VAR:89}

fees:
  threshold-low: ${THRESHOLD_LOW:1000}
  threshold-high: ${THRESHOLD_HIGH:5000}
  rate-low: ${RATE_LOW:0.015}
  rate-mid: ${RATE_MID:0.01}
  rate-high: ${RATE_HIGH:0.005}
